version: '3.9'

services:
  #   rabbitmq:
  #     image: rabbitmq:3-management-alpine
  #     container_name: 'rabbitmq'
  #     ports:
  #       - 5672:5672
  #       - 15672:15672
  #     volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  #     networks:
  #       - rabbitmq_go_net

  crdb_node_1:
    container_name: crdb_node_1
    image: cockroachdb/cockroach:latest
    volumes:
      - ./data/node_1:/cockroach/cockroach-data
    # command: start --insecure
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      network_cockroachdb:
        aliases:
          - crdb_node_1
  # crdb_node_2:
  #   container_name: crdb_node_2
  #   image: cockroachdb/cockroach:latest
  #   volumes:
  #     - ./data/node_2:/cockroach/cockroach-data
  #   command: start --insecure --join=crdb_node_1
  #   networks:
  #     network_cockroachdb:
  #       aliases:
  #         - crdb_node_2

networks:
  network_cockroachdb:
    driver: bridge
  # rabbitmq_go_net:
  #   driver: bridge
